version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Mappe le port 8080 de l'hôte au port 80 du conteneur
    volumes:
      - ./html:/usr/share/nginx/html # Montre le répertoire local HTML dans le conteneur
      - ./nginx.conf:/etc/nginx/nginx.conf # Montre le fichier de config nginx
    restart: always
